In [97]:
#Установка нужных пакетов
#pip install --upgrade nltk gensim bokeh umap-learn

import itertools
import string

import numpy as np
import umap
from nltk.tokenize import WordPunctTokenizer

from matplotlib import pyplot as plt

from IPython.display import clear_output

In [98]:
# выгружаем датасет:
#wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

In [99]:
data = list(open("./quora.txt", encoding="utf-8"))
data[1]

'What are some ways to overcome a fast food addiction?\n'

In [100]:
tokenizer = WordPunctTokenizer()

print(tokenizer.tokenize(data[1]))

['What', 'are', 'some', 'ways', 'to', 'overcome', 'a', 'fast', 'food', 'addiction', '?']


#Задание 1: Перевести все слова в нижний регистр (NLTK) из data и добавьте как лист токенов в листе data_tok


In [101]:
data_tok = list()
for a in data:
    current_token = tokenizer.tokenize(a)
    row = list()
    for b in current_token:
        row.append(b.lower())
    data_tok.append(row)

#checking

assert all(isinstance(row, (list, tuple)) for row in data_tok), "please convert each line into a list of tokens (strings)"
is_latin = lambda tok: all('a' <= x.lower() <= 'z' for x in tok)
assert all(map(lambda l: not is_latin(l) or l.islower(), map(' '.join, data_tok))), "please make sure to lowercase the data"


###Задание 2: Подсчитайте топ10 самых популярных лем в рамках data

In [102]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /Users/max/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /Users/max/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [103]:
all_tokens = list()
for a in data_tok:
    all_tokens.extend(a)
dict = nltk.FreqDist(all_tokens)
len_dict = len(dict)
print(f'vocabulary size: {len_dict}')
top10 = dict.most_common(80000)
top10

vocabulary size: 87820


[('?', 552413),
 ('the', 252068),
 ('what', 214798),
 ('is', 185392),
 ('a', 155726),
 ('i', 149735),
 ('to', 141788),
 ('in', 139787),
 ('how', 135687),
 ('of', 112001),
 ('do', 104282),
 ('are', 98049),
 ('and', 89442),
 ('for', 74801),
 ('can', 73702),
 (',', 72487),
 ('you', 60753),
 ("'", 57241),
 ('why', 56211),
 ('.', 52961),
 ('it', 52425),
 ('my', 45184),
 ('best', 40992),
 ('does', 39619),
 ('on', 38005),
 ('or', 33240),
 ('s', 31078),
 ('if', 30446),
 ('have', 30277),
 ('be', 29521),
 ('with', 29149),
 ('which', 29045),
 ('that', 28454),
 ('an', 28022),
 ('some', 27382),
 ('-', 26910),
 ('should', 26529),
 ('get', 25827),
 ('from', 25273),
 ('"', 21714),
 ('your', 20585),
 ('(', 19478),
 ('like', 19049),
 ('when', 18923),
 ('at', 18343),
 ('india', 18334),
 ('good', 17685),
 ('who', 17517),
 ('there', 17170),
 ('will', 16860),
 ('as', 16787),
 ('t', 16785),
 ('people', 16398),
 ('would', 16389),
 ('not', 15325),
 ('/', 15038),
 ('about', 14416),
 ('between', 13959),
 ('one',

###Задание 3: Подсчитайте количество разных слов до и после лемматизации

In [104]:
count_before_lemm = len(all_tokens)
after_lemm = set()
for a in all_tokens:
    after_lemm.add(lemmatizer.lemmatize(a))
count_after_lemm = len(after_lemm)
print(f'Before lemmatization: {count_before_lemm}, after lemmatization: {count_after_lemm}')


Before lemmatization: 7131337, after lemmatization: 80304


###Задание 4: Подсчитайте количество разных слов до и после стемминга

In [105]:
count_before_stemm = len(all_tokens)
after_stemm = set()
for a in all_tokens:
    after_stemm.add(ps.stem(a))
count_after_stemm = len(after_stemm)
print(f'Before stemming: {count_before_stemm}, after stemming: {count_after_stemm}')

Before stemming: 7131337, after stemming: 67026


###Задание 5: Подсчитайте количество разных слов



In [106]:
stem_after_lemm = set()
for a in after_lemm:
    stem_after_lemm.add(ps.stem(a))
count_stem_after_lem = len(stem_after_lemm)

lemm_after_stem = set()
for a in after_stemm:
    lemm_after_stem.add(lemmatizer.lemmatize(a))
count_lemm_after_stem = len(lemm_after_stem)

print(f'Count stem after lem: {count_stem_after_lem}, count lem after stem: {count_lemm_after_stem}')

Count stem after lem: 66835, count lem after stem: 66818


REGEXP

https://www.programiz.com/python-programming/regex 

https://docs.python.org/3/howto/regex.html

In [107]:
import re

pattern = 'a*s'
test_string = 'abyss'
result = re.match(pattern, test_string)

if result:
  print("Search successful.")
else:
  print("Search unsuccessful.")	

Search unsuccessful.


In [108]:
###Задание 6: 
###https://www.hackerrank.com/challenges/matching-specific-string/problem?isFullScreen=true 
def check_hackerrank(t: str):
    p = re.compile('.*?hackerrank.*?')
    if p.match(t):
        print(f'MATCH: str: {t} contains the word hackerrank')
        return True
    else:
        print(f'MISSS: str: {t} doesn\'t contain the word hackerrank')
        return False

assert check_hackerrank('hackerrank bla bla bla ') #start
assert check_hackerrank('not as good as hackerrank') # end
assert not check_hackerrank('does not contains hacker_rank') # missed


MATCH: str: hackerrank bla bla bla  contains the word hackerrank
MATCH: str: not as good as hackerrank contains the word hackerrank
MISSS: str: does not contains hacker_rank doesn't contain the word hackerrank


In [109]:

###Задание 7: 
###https://www.hackerrank.com/challenges/matching-whitespace-non-whitespace-character/problem?isFullScreen=true
### implement pattern XX_XX_XX

def check_pattern(t: str):
    tt = re.compile('^(..)\s(..)\s(..)$')
    return tt.match(t)

assert check_pattern('10 11 12')
assert check_pattern('df 12 f5')
assert not check_pattern(' . df 23 gd ')

In [110]:
###Задание 8: 
###https://www.hackerrank.com/challenges/matching-start-end/problem?isFullScreen=true
def check_pattern_task8(t: str):
    tt = re.compile('^(\d)(\D{6})\.$')
    return tt.match(t)

assert check_pattern_task8('9mmmmmm.')
assert not check_pattern_task8(' 9mmmmmm.')
assert not check_pattern_task8('9mmmmmmm.')
assert not check_pattern_task8('9mmmmmmm')
assert not check_pattern_task8(' 9mmmmm. ')

In [111]:
###Задание 9: 
###https://www.hackerrank.com/challenges/matching-word-boundaries/problem?isFullScreen=true
###You have a test String .
##Your task is to write a regex which will match word starting with vowel (a,e,i,o, u, A, E, I , O or U).
##The matched word can be of any length. The matched word should consist of letters (lowercase and uppercase both) only.
##The matched word must start and end with a word boundary.

def check_pattern_task9(t: str):
    tt = re.compile('^[aeiouAEIOU]\S+$')
    return tt.match(t)

assert check_pattern_task9('aLFLFLFLF')
assert not check_pattern_task9('bLFLFLFLF')
assert not check_pattern_task9('bLFLF LFLF')
assert not check_pattern_task9('9bLFLF LFLF')
assert not check_pattern_task9(' 9bLFLF LFLF')


Bag Of Words (BOW)

In [112]:
def vectorize(tokens):
    ''' This function takes list of words in a sentence as input 
    and returns a vector of size of filtered_vocab.It puts 0 if the 
    word is not present in tokens and count of token if present.'''
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector
def unique(sequence):
    '''This functions returns a list in which the order remains 
    same and no item repeats.Using the set() function does not 
    preserve the original ordering,so i didnt use that instead'''
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]

#create a list of stopwords.You can import stopwords from nltk too
stopwords=["to","is","a"]

#list of special characters.You can use regular expressions too
special_char=[",",":"," ",";",".","?"]

#Write the sentences in the corpus,in our case, just two 
string1="Welcome to Great Learning , Now start learning"
string2="Learning is a good practice"

#convert them to lower case
string1=string1.lower()
string2=string2.lower()

#split the sentences into tokens
tokens1=string1.split()
tokens2=string2.split()
print(tokens1)
print(tokens2)

#create a vocabulary list
vocab=unique(tokens1+tokens2)
# print(vocab)

#filter the vocabulary list
filtered_vocab=[]
for w in vocab: 
    if w not in stopwords and w not in special_char: 
        filtered_vocab.append(w)
print(f'filtered vocabulary: {filtered_vocab}')

#convert sentences into vectords
vector1=vectorize(tokens1)
print(vector1)
vector2=vectorize(tokens2)
print(vector2)

['welcome', 'to', 'great', 'learning', ',', 'now', 'start', 'learning']
['learning', 'is', 'a', 'good', 'practice']
filtered vocabulary: ['welcome', 'great', 'learning', 'now', 'start', 'good', 'practice']
[1, 1, 2, 1, 1, 0, 0]
[0, 0, 1, 0, 0, 1, 1]


Задание 10: Реализовать Bag of words на data_tok (можно на NLTK, можно без)

In [113]:
###https://www.geeksforgeeks.org/bag-of-words-bow-model-in-nlp/
from numpy import dot
from numpy.linalg import norm

X = []

t = 0
vocabulary = top10
for data_loc in data_tok:
    if t==50:
        break
    t+=1
    vector = []
    for word_ in vocabulary:
        word = word_[0]
        if word in data_loc:
            vector.append(data_loc.count(word))
        else:
            vector.append(0)
    X.append(vector)
X = np.asarray(X)

# for a in range(50):
#     print(f'sentence: {data[a]}')

index1 = 0
index2 = 0  
max_value = 0 

for a in range(50):
    for b in range(a+1, 50):
        cur_res  = dot(X[a], X[b])/(norm(X[a])*norm(X[b]))
        if cur_res > max_value:
            max_value = cur_res
            index1 = a
            index2 = b

print(f'The most similar sentences with score: {max_value} are: ' )
print(f'{data[index1]}')
print(f'{data[index2]}')


The most similar sentences with score: 0.7559289460184544 are: 
What is your review of osquery?

What is your review of iPad Mini 2?



In [114]:
# text=["kolkata big city india trade","mumbai financial capital india","delhi capital india","kolkata capital colonial times",
#      "bangalore tech hub india software","mumbai hub trade commerce stock exchange","kolkata victoria memorial","delhi india gate",
#       "mumbai gate way india trade business","delhi red fort india","kolkata metro oldest india",
#       "delhi metro largest metro network india"]
counter = 0
text_list = list()
for a in data_tok:
    counter+=1
    if counter == 50:
        break;
    t = ' '.join(a)
    text_list.append(t)
text = text_list


In [115]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [116]:
#using the count vectorizer
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)
print(word_count.toarray())

  (0, 37)	1
  (0, 100)	1
  (0, 26)	1
  (0, 260)	2
  (0, 159)	1
  (0, 81)	1
  (0, 79)	1
  (0, 228)	1
  (0, 206)	1
  (0, 129)	1
  (0, 186)	1
  (0, 12)	1
  (0, 109)	1
  (0, 25)	1
  (1, 252)	1
  (1, 14)	1
  (1, 214)	1
  (1, 247)	1
  (1, 231)	1
  (1, 178)	1
  (1, 87)	1
  (1, 92)	1
  (1, 6)	1
  (2, 256)	2
  (2, 251)	1
  :	:
  (46, 100)	1
  (46, 9)	1
  (46, 19)	1
  (46, 114)	1
  (46, 202)	1
  (46, 220)	1
  (46, 126)	1
  (46, 105)	1
  (46, 201)	1
  (47, 14)	1
  (47, 256)	1
  (47, 226)	1
  (47, 122)	1
  (47, 35)	1
  (47, 232)	1
  (47, 50)	1
  (47, 22)	1
  (48, 231)	1
  (48, 257)	1
  (48, 63)	1
  (48, 93)	1
  (48, 101)	1
  (48, 244)	1
  (48, 33)	1
  (48, 189)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [117]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])

/Users/max/miniforge3/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [118]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights'])


idf_weights
the         2.021651
is          2.139434
how         2.139434
what        2.203973
can         2.427116
...              ...
goal        4.218876
goldman     4.218876
graphic     4.218876
martin      4.218876
zotac       4.218876

[269 rows x 1 columns]

In [119]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)

/Users/max/miniforge3/envs/tensorflow/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
fast       0.375854
food       0.375854
addiction  0.375854
some       0.375854
ways       0.375854
...             ...
from       0.000000
george     0.000000
get        0.000000
girls      0.000000
zotac      0.000000

[269 rows x 1 columns]